"use strict";

module.exports = {
	LOGIN: 'LOGIN', 
	LOGOUT: 'LOGOUT',
	GET_USER: 'GET_USER',
	INITIALIZE: 'INITIALIZE',

	PRESENTATION_GET: 'PRESENTATION_GET',
	PRESENTATION_CREATE: 'PRESENTATION_CREATE',
	PRESENTATION_GET_ALL: 'PRESENTATION_GET_ALL',
	PRESENTATION_UPDATE: 'PRESENTATION_UPDATE'
};